In [1]:
import numpy as np
import pandas as pd

In [22]:
np.random.seed(0) # pour éviter le changement de la matrice à chaque recompilation
A = np.random.randint(0,9, [5,4])
A

array([[5, 0, 3, 3],
       [7, 3, 5, 2],
       [4, 7, 6, 8],
       [8, 1, 6, 7],
       [7, 8, 1, 5]])

In [71]:
A.mean()

4.8

In [72]:
A.std()

2.4819347291981715

In [73]:
A.var()

6.16

In [15]:
A.shape

(5, 4)

In [16]:
A.max()

8

In [17]:
A.min()

0

In [18]:
A.argmin()

1

In [8]:
A.argmax()

5

In [19]:
np.corrcoef(A)

array([[ 1.        ,  0.67451348, -0.63906444,  0.96209429, -0.2480959 ],
       [ 0.67451348,  1.        , -0.99026741,  0.459334  , -0.06070089],
       [-0.63906444, -0.99026741,  1.        , -0.40804713, -0.07881104],
       [ 0.96209429,  0.459334  , -0.40804713,  1.        , -0.36363977],
       [-0.2480959 , -0.06070089, -0.07881104, -0.36363977,  1.        ]])

In [20]:
A

array([[5, 0, 3, 3],
       [7, 3, 5, 2],
       [4, 7, 6, 8],
       [8, 1, 6, 7],
       [7, 8, 1, 5]])

In [21]:
np.unique(A, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([1, 2, 1, 3, 1, 3, 2, 4, 3], dtype=int64))

In [59]:
values, counts = np.unique(A,return_counts=True)

In [60]:
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
counts

array([1, 2, 1, 3, 1, 3, 2, 4, 3], dtype=int64)

In [62]:
counts.argsort()

array([0, 2, 4, 1, 6, 3, 5, 8, 7], dtype=int64)

In [65]:
C = counts[counts.argsort()]
C

array([1, 1, 1, 2, 2, 3, 3, 3, 4], dtype=int64)

In [66]:
D =values[counts.argsort()]
D

array([0, 2, 4, 1, 6, 3, 5, 8, 7])

In [70]:
for i, j in zip(C, D) :
    print(f'L\'élement {j} apparait {i} fois dans la matrice A')

L'élement 0 apparait 1 fois dans la matrice A
L'élement 2 apparait 1 fois dans la matrice A
L'élement 4 apparait 1 fois dans la matrice A
L'élement 1 apparait 2 fois dans la matrice A
L'élement 6 apparait 2 fois dans la matrice A
L'élement 3 apparait 3 fois dans la matrice A
L'élement 5 apparait 3 fois dans la matrice A
L'élement 8 apparait 3 fois dans la matrice A
L'élement 7 apparait 4 fois dans la matrice A


In [74]:
# counts.sort()
# counts

In [76]:
[A>4]

[array([[ True, False, False, False],
        [ True, False,  True, False],
        [False,  True,  True,  True],
        [ True, False,  True,  True],
        [ True,  True, False,  True]])]

In [82]:
E = np.random.randn(4,3)
E

array([[-0.40602374,  0.26644534, -1.35571372],
       [-0.11410253, -0.84423086,  0.70564081],
       [-0.39878617, -0.82719653, -0.4157447 ],
       [-0.52451219,  0.81310127, -0.22925063]])

In [84]:
E[E>0.5] = np.nan
E

array([[-0.40602374,  0.26644534, -1.35571372],
       [-0.11410253, -0.84423086,         nan],
       [-0.39878617, -0.82719653, -0.4157447 ],
       [-0.52451219,         nan, -0.22925063]])

In [85]:
E.mean()

nan

In [88]:
np.nanmean(E)

-0.4849115746846796

In [89]:
np.nanstd(E)

0.4233152430148088

In [90]:
np.nanvar(E)

0.17919579496868662

In [91]:
np.isnan(E)

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False,  True, False]])

In [94]:
l = np.isnan(E).sum()
l

2

In [97]:
l/E.size

0.16666666666666666

In [98]:
E.shape

(4, 3)

In [99]:
E.size

12

In [100]:
E[np.isnan(E)] = 0

In [101]:
E

array([[-0.40602374,  0.26644534, -1.35571372],
       [-0.11410253, -0.84423086,  0.        ],
       [-0.39878617, -0.82719653, -0.4157447 ],
       [-0.52451219,  0.        , -0.22925063]])

# Algèbre linéaire

In [107]:
M = np.random.randint(0,9, [4,3])
print(M) 
print('\n')
N =np.random.randint(0,9, [3,4])
print(N)

[[8 4 6]
 [5 8 2]
 [3 7 5]
 [3 4 5]]


[[3 3 7 7]
 [3 2 3 7]
 [7 5 1 2]]


In [109]:
M.dot(N)

array([[78, 62, 74, 96],
       [53, 41, 61, 95],
       [65, 48, 47, 80],
       [56, 42, 38, 59]])

In [110]:
N.dot(M)

array([[ 81, 113,  94],
       [ 64,  77,  72],
       [ 90,  83,  67]])

In [111]:
M.T

array([[8, 5, 3, 3],
       [4, 8, 7, 4],
       [6, 2, 5, 5]])

In [115]:
G = np.random.randint(0,9,[3,3])

In [116]:
np.linalg.det(G)

-126.0

In [117]:
np.linalg.inv(G)

array([[-0.25396825,  0.3015873 , -0.19047619],
       [ 0.1984127 , -0.07936508,  0.02380952],
       [-0.07936508,  0.03174603,  0.19047619]])

In [118]:
np.linalg.pinv(G)

array([[-0.25396825,  0.3015873 , -0.19047619],
       [ 0.1984127 , -0.07936508,  0.02380952],
       [-0.07936508,  0.03174603,  0.19047619]])

In [119]:
np.linalg.pinv(M)

array([[ 0.15644107,  0.0820156 , -0.133249  , -0.08728653],
       [-0.09453932,  0.10946658,  0.07459414, -0.00493359],
       [ 0.01349357, -0.17351887,  0.10710521,  0.14611006]])

In [120]:
np.linalg.eig(G)

(array([12.83205799, -2.23177186,  4.39971387]),
 array([[-0.59402512,  0.86934523, -0.48809394],
        [-0.77943469, -0.47632525, -0.25090439],
        [-0.19903701,  0.13173127,  0.83594933]]))

# TP   Standardisation (important)

In [127]:
M

array([[8, 4, 6],
       [5, 8, 2],
       [3, 7, 5],
       [3, 4, 5]])

In [129]:
M.mean(axis=0)

array([4.75, 5.75, 4.5 ])

In [130]:
P= M - M.mean(axis=0)
P

array([[ 3.25, -1.75,  1.5 ],
       [ 0.25,  2.25, -2.5 ],
       [-1.75,  1.25,  0.5 ],
       [-1.75, -1.75,  0.5 ]])

In [131]:
S = P/M.std(axis=0)
S # standardisation

array([[ 1.58820278, -0.98019606,  1.        ],
       [ 0.12216944,  1.26025208, -1.66666667],
       [-0.85518611,  0.70014004,  0.33333333],
       [-0.85518611, -0.98019606,  0.33333333]])