In [1]:
import numpy as np

In [11]:
A = np.array([[4,1,8],[5,2,5], [2, 6,7], [9,7,4]])
A.shape

(4, 3)

In [18]:
B = np.zeros((3,6))
B.shape

(3, 6)

In [20]:
type(B.shape)

tuple

In [21]:
B.ndim

2

In [24]:
C = np.ones((5,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
D = np.full((3,4),5)
D

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
E = np.random.randn(2,3)
E

array([[ 0.44828717,  1.37338995, -0.90890125],
       [ 0.53238208, -0.05340801,  0.0595381 ]])

In [31]:
F = np.eye(4)
F

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
G = np.linspace(1, 30, 15, dtype=np.float64)
G

array([ 1.        ,  3.07142857,  5.14285714,  7.21428571,  9.28571429,
       11.35714286, 13.42857143, 15.5       , 17.57142857, 19.64285714,
       21.71428571, 23.78571429, 25.85714286, 27.92857143, 30.        ])

In [38]:
H = np.arange(0, 30, 1.5)
H

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5, 24. , 25.5, 27. , 28.5])

In [49]:
S = np.random.randn(2,3)
S

array([[-0.96814271, -1.24207815,  0.78289411],
       [ 1.837831  , -1.25328392, -0.15669075]])

In [59]:
T = np.random.randn(2,3)
T

array([[ 1.06203457, -0.17509055, -0.98444214],
       [ 0.91128894,  0.05001278,  1.25373634]])

In [60]:
T.size

6

In [63]:
T.shape

(2, 3)

In [55]:
U = np.concatenate((S,T), axis=1)
U

array([[-0.96814271, -1.24207815,  0.78289411, -0.51158547, -1.32269796,
        -1.21539182],
       [ 1.837831  , -1.25328392, -0.15669075, -0.50456245, -0.9811921 ,
        -0.38662742]])

In [61]:
U.size

12

In [62]:
U.shape

(2, 6)

In [64]:
U.reshape(4,3)

array([[-0.96814271, -1.24207815,  0.78289411],
       [-0.51158547, -1.32269796, -1.21539182],
       [ 1.837831  , -1.25328392, -0.15669075],
       [-0.50456245, -0.9811921 , -0.38662742]])

In [65]:
U.reshape(6,2)

array([[-0.96814271, -1.24207815],
       [ 0.78289411, -0.51158547],
       [-1.32269796, -1.21539182],
       [ 1.837831  , -1.25328392],
       [-0.15669075, -0.50456245],
       [-0.9811921 , -0.38662742]])

In [67]:
D.ravel().shape

(12,)

In [116]:
def initialize(m,n):
    K = np.random.randn(m,n)
    P = np.ones((K.shape[0],1))
    L = np.concatenate((P,K), axis=1)
    return L

In [117]:
ligne = int(input('Donnez le nombre de lignes : '))
colonne = int(input('Donnez le nombre de colonnes : '))
initialize(ligne, colonne)

Donnez le nombre de lignes : 3
Donnez le nombre de colonnes : 4


array([[ 1.        , -1.32665162,  1.03996031, -1.03372615,  0.19403336],
       [ 1.        , -1.04959287, -1.38263459,  0.81577316, -0.71561876],
       [ 1.        , -2.22610117,  0.09159716, -0.75936521,  0.33394257]])

In [107]:
def initialisation(m,n):
    K = np.random.randn(m,n)
    K = np.concatenate((np.ones((K.shape[0],1)),K), axis=1)
    return K

In [108]:
initialisation(4,3)

array([[ 1.        ,  1.50682238, -1.74249469, -0.40585044],
       [ 1.        , -0.40464183, -1.08537914, -2.28485291],
       [ 1.        , -1.23769495, -1.87032614, -0.11843221],
       [ 1.        ,  2.26809196,  1.18802934,  0.13766129]])